// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClC_AhAHUi_usauimxqe77BqPfSZ0bF_A',
    appId: '1:804996633366:web:31337da5f9809e2b47f637',
    messagingSenderId: '804996633366',
    projectId: 'livenotes-a3890',
    authDomain: 'livenotes-a3890.firebaseapp.com',
    storageBucket: 'livenotes-a3890.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTpnUjUbqIu7TGb_ucZvOJWXgKTaA5etw',
    appId: '1:804996633366:android:d44f2dbde5f5426e47f637',
    messagingSenderId: '804996633366',
    projectId: 'livenotes-a3890',
    storageBucket: 'livenotes-a3890.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9xM_Rq5nWHw2M5pyqsSysN9MwGhNIkn4',
    appId: '1:804996633366:ios:602c740ad035f0ad47f637',
    messagingSenderId: '804996633366',
    projectId: 'livenotes-a3890',
    storageBucket: 'livenotes-a3890.firebasestorage.app',
    iosBundleId: 'com.example.liveNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9xM_Rq5nWHw2M5pyqsSysN9MwGhNIkn4',
    appId: '1:804996633366:ios:602c740ad035f0ad47f637',
    messagingSenderId: '804996633366',
    projectId: 'livenotes-a3890',
    storageBucket: 'livenotes-a3890.firebasestorage.app',
    iosBundleId: 'com.example.liveNotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClC_AhAHUi_usauimxqe77BqPfSZ0bF_A',
    appId: '1:804996633366:web:629463ca605d6dd747f637',
    messagingSenderId: '804996633366',
    projectId: 'livenotes-a3890',
    authDomain: 'livenotes-a3890.firebaseapp.com',
    storageBucket: 'livenotes-a3890.firebasestorage.app',
  );
}
